server.port=28090
spring.application.name=dubbo-java-provider-demo
spring.profiles.active=${NACOS_NAMESPACE}
spring.main.lazy-initialization=true

spring.config.import=optional:nacos:${spring.application.name}?refreshEnabled=true
spring.cloud.nacos.discovery.server-addr=${NACOS_SERVER_ADDR}
spring.cloud.nacos.discovery.namespace=${spring.profiles.active}
spring.cloud.nacos.config.server-addr=${spring.cloud.nacos.discovery.server-addr}
spring.cloud.nacos.config.namespace=${spring.profiles.active}
spring.cloud.nacos.username=${NACOS_USERNAME}
spring.cloud.nacos.password=${NACOS_PASSWORD}

dubbo.registry.address=nacos://${spring.cloud.nacos.discovery.server-addr}?namespace=${spring.profiles.active}
dubbo.application.register-mode=interface
dubbo.application.name=${spring.application.name}-dubbo
dubbo.application.qos-enable=false
dubbo.application.serialize-check-status=DISABLE
dubbo.application.check-serializable=false
dubbo.protocol.name=tri
dubbo.protocol.port=${DUBBO_PROTOCOL_PORT:27090}
dubbo.protocol.triple.rest.enabled=true
dubbo.protocol.triple.rest.openapi.enabled=true
dubbo.protocol.triple.rest.openapi.path=/dubbo/docs/helloworld
dubbo.consumer.check=false
dubbo.consumer.timeout=5000

