// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: helloworld.proto
package pb

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// HelloWorldServiceName is the fully-qualified name of the HelloWorldService service.
	HelloWorldServiceName = "pb.HelloWorldService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HelloWorldServiceSayHelloProcedure is the fully-qualified name of the HelloWorldService's SayHello RPC.
	HelloWorldServiceSayHelloProcedure = "/pb.HelloWorldService/SayHello"
)

var (
	_ HelloWorldService = (*HelloWorldServiceImpl)(nil)
)

// HelloWorldService is a client for the pb.HelloWorldService service.
type HelloWorldService interface {
	SayHello(ctx context.Context, req *HelloRequest, opts ...client.CallOption) (*HelloReply, error)
}

// NewHelloWorldService constructs a client for the pb.HelloWorldService service.
func NewHelloWorldService(cli *client.Client, opts ...client.ReferenceOption) (HelloWorldService, error) {
	conn, err := cli.DialWithInfo("pb.HelloWorldService", &HelloWorldService_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &HelloWorldServiceImpl{
		conn: conn,
	}, nil
}

func SetConsumerHelloWorldService(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &HelloWorldService_ClientInfo)
}

// HelloWorldServiceImpl implements HelloWorldService.
type HelloWorldServiceImpl struct {
	conn *client.Connection
}

func (c *HelloWorldServiceImpl) SayHello(ctx context.Context, req *HelloRequest, opts ...client.CallOption) (*HelloReply, error) {
	resp := new(HelloReply)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "SayHello", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var HelloWorldService_ClientInfo = client.ClientInfo{
	InterfaceName: "pb.HelloWorldService",
	MethodNames:   []string{"SayHello"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*HelloWorldServiceImpl)
		dubboCli.conn = conn
	},
}

// HelloWorldServiceHandler is an implementation of the pb.HelloWorldService service.
type HelloWorldServiceHandler interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterHelloWorldServiceHandler(srv *server.Server, hdlr HelloWorldServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &HelloWorldService_ServiceInfo, opts...)
}

func SetProviderHelloWorldService(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &HelloWorldService_ServiceInfo)
}

var HelloWorldService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "pb.HelloWorldService",
	ServiceType:   (*HelloWorldServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "SayHello",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(HelloRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*HelloRequest)
				res, err := handler.(HelloWorldServiceHandler).SayHello(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
